---
author: null
banner: ""
categories: []
date: 2019-10-19
description: 
images: []
menu: ""
slug: internship
title: "A la recherche d'un stage pour l'été 2020"
---

<center>
```{r echo=FALSE}
blogdown::shortcode('tweet', '1175516407376875522')
```
</center>

<!--more-->

Après près de **5 ans d’expérience professionnelle dans la statistique publique**, je retourne quelques temps sur les bancs de l’école suite à l’obtention du concours d’administrateur statisticien de l’Insee. 

Je recherche un **stage de 10 à 12 semaines (entre le 1er Juin et le 25 septembre) en Data Science** à partir de juin 2020 qui me permettra d’enrichir encore davantage mes connaissances en implémentation informatique de méthodes et d’outils statistiques. 

Mon rêve serait de le faire **en dehors de l'Europe**. Je ne recherche pas exclusivement des stages rémunérés. Toutefois, si je pouvais avoir une aide financière (en particulier pour le visa, le voyage et le logement), cela m'aiderait beaucoup. 

Pour répondre aux exigences de l'école où j'étudie ([ENSAE Paris](https://www.ensae.fr/)), je dois juste **utiliser des méthodes statistiques** basées sur les enseignements de l'école, ce qui peut couvrir un **large éventail de sujets**.

J'ai de l'expérience principalement en **analyse spatiale, enquêtes d'opinion et en datavisualisation**. Ces compétences peuvent être mobilisées et renforcées , mais je suis très flexible et ouverte pour travailler dans d'autres domaines.

Passionnée par l’**open-data et l’open-source**, en plus d'assister à des Meet-up comme **@RLadiesParis** ou **@ParisRAddict**, je réalise également des projets en ce sens sur mon temps personnel, mobilisant le **logiciel statistique R**. 


Mes trois principaux projets sont : 

  - [**Application web Baromètre R Shiny**](http://dataviz.drees.solidarites-sante.gouv.fr/Barometre-DREES/) : graphiques interactifs des résultats du Baromètre d'opinion de la DREES.</br></br>
 - [**COGugaison**](https://github.com/antuki/COGugaison) : Package R utile à la gestion des codes officiels géographiques (COG) dans les tables de données géographiques.</br></br>
 - [**CARTElette**](https://github.com/antuki/CARTElette) : Package R de création de couches cartographiques à partir du code officiel géographique (COG) et des couches IGN. 

Voici mon CV : [HTML](https://antuki.github.io/slides/CV/CV4.html)  / [PDF](https://antuki.github.io/slides/CV/CV_ANTUNEZ_online.pdf)
 
**Merci** pour tous les conseils que vous pourrez me donner pour cette recherche !