---
author: null
banner: ""
categories: []
date: 2019-10-19
description: "<center><blockquote class='twitter-tweet'><p lang='en' dir='ltr'>🎤Looking for a 2020 Summer <a href='https://twitter.com/hashtag/internship?src=hash&amp;ref_src=twsrc%5Etfw'>#internship</a> in <a href='https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw'>#DataScience</a>.  Back in school <a href='https://twitter.com/ENSAEparis?ref_src=twsrc%5Etfw'>@ENSAEparis</a> after five years of professional experience in French official statistics. Preferably in 🇺🇸🇨🇦🇦🇺 Many personal <a href='https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw'>#rstats</a> projects on my github and LinkedIn. <a href='https://t.co/NZP2I7o2LT'>https://t.co/NZP2I7o2LT</a> <a href='https://t.co/8PXNbCUFvV'>pic.twitter.com/8PXNbCUFvV</a></p>&mdash; antuki (@antuki13) <a href='https://twitter.com/antuki13/status/1175516407376875522?ref_src=twsrc%5Etfw'>September 21, 2019</a></blockquote><script async src='https://platform.twitter.com/widgets.js' charset='utf-8'></script></center>"
images: []
menu: ""
slug: internship
title: 'Looking for a summer 2020 internship'
---

<center>
```{r echo=FALSE}
blogdown::shortcode('tweet', '1175516407376875522')
```
</center>

After **5 years of professional experience in official statistics**, I am back in school to complete my training to become a Senior Officer for the French National Institute of Statistics and Economic Studies (INSEE), after recently passing the internal competitive exam.

I am looking for a **10-12-week summer internship in Data Science between June 1st and September 25th, 2020** starting in June 2020 to improve and further develop my knowledge in IT implementation of statistical methods and tools. 

My dream would be to do it **outside Europe**. I'm not exclusively looking for a paid internship. However if I could have a financial assistance (especially for the visa, trip and the accommodation), it would be really helpful.

To fulfill the requirements of the school where I'm studying ([ENSAE Paris](https://www.ensae.fr/en/)), I just have to **apply statistical methods** based on the teachings of the school, which means it can cover a **large scope of topics**.
 
I mainly have experience in **spatial analysis, opinion polls and datavisualisation**. These skills can be enforced during the internship, but I'm very flexible and open to work in other areas.

Passionate about **open data and open source**, in addition to going to meetings such as **@RLadiesParis** or **@ParisRAddict**, I’ve also worked on different personal projects using **R (statistical software)**. My three main open source projects are:

 - [**R Shiny Web application**](http://dataviz.drees.solidarites-sante.gouv.fr/Barometre-DREES/): interactive graphs of the French Opinion Barometer results. </br></br>
 - [**COGugaison**](https://github.com/antuki/COGugaison):  R package for manipulating French spatial databases produced at different dates. </br></br>
 - [**CARTElette**](https://github.com/antuki/CARTElette): R package for creating geographical layers that correspond to the situation of the division of the French territories of each year.

Here is my resume: [HTML](https://antuki.github.io/slides/CV/CV4.html)  / [PDF](https://antuki.github.io/slides/CV/CV_ANTUNEZ_online.pdf)
 

**Thank you** for all the advice you could give me for this search!

